### ISSUE TITLE
Handle exception in csbuild if git tree is dirty

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#14]
csbuild should now throw and exception if the git tree is dirtry

```
/usr/bin/csbuild: warning: git repository is dirty: .
/usr/bin/csbuild: status: checking out origin/master
Traceback (most recent call last):
  File "/usr/bin/csbuild", line 488, in <module>
    main()
  File "/usr/bin/csbuild", line 436, in main
    do_git_checkout(repo, old_commit)
  File "/usr/bin/csbuild", line 161, in do_git_checkout
    repo.git.checkout(commit)
  File "/usr/lib/python3.6/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.6/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout origin/master
  stderr: 'error: Your local changes to the following files would be overwritten by checkout:                                                                            
        .gitlab-ci.yml
Please commit your changes or stash them before you switch branches.
Aborting'
```

**Comment by kdudka** [comment]
How do you propose to handle it?  Run `git stash` before the first checkout and `git stash pop --index` after completion?

For this to work, we should probably also checkout the branch (or detached HEAD) that was active before running csbuild, to restore the state that the stash applies to.  As it is now, `csbuild -g OLD_REV..NEW_REV ...` results in `NEW_REV` being checked out on exit.

Another similar failure could happen if a local non-tracked file would be in the way of a file to be created by `git checkout`.  Should we handle such case, too?  How?

**Comment by cryptomilk** [comment]
I meant that python should not throw an exception but handle it gracefully and just print a nice error. The backtrace is ugly from a user perspective :-)

**Comment by kdudka** [comment]
Letting users deal with the failure themselves is certainly easier.  After all, it is what tools like `git rebase` or `git bisect` also do.  So I will just sanitize the error message...
