### ISSUE TITLE
csdiff incompatible pylint output from run-pylint.sh

### ISSUE THREAD

**Issue by praiskup** [kdudka/csmock#25]
I tried to run run-pylint.sh with fixed list of files to scan:
`$ /usr/share/csmock/scripts/run-pylint.sh tests/test_modifyrepo.py tests/test_sign.py`

And there's  output like:
```
...
************* Module tests.test_sign
/home/praiskup/rh/projects/copr/copr/backend/tests/test_sign.py:194:0: C0330[pylint]: Wrong continued indentation (remove 5 spaces).
                                      tmp_dir, tmp_files):
                                 |    ^
...
/home/praiskup/rh/projects/copr/copr/backend/tests/test_sign.py:12:0: C0411[pylint]: standard import "from unittest.mock import MagicMock" should be placed before "from munch import Munch"
-----------------------------------
Your code has been rated at 7.56/10
...
```

csdiff isn't able to parse that:
```
$ csdiff /tmp/a /tmp/a
/tmp/a:1: error: invalid syntax
....
```

**Comment by praiskup** [comment]
The `--score=no` option could help (if it is available for particular pylint version).
I don't know how to filter out the `******* MODULENAME` output (other then `grep -v`).

**Comment by praiskup** [comment]
I eventually went with alternative:
https://pagure.io/copr/copr/blob/master/f/build_aux/csdiff-pylint

That's easier because we can rely on new enough pylint.  In csmock
case, it's probably matter of ./configure time checking.

**Comment by kdudka** [comment]
Is this really an issue for end users of csmock?

All the extra output should be filtered out by `csgrep --quiet` in the post processing hook:

https://github.com/kdudka/csmock/blob/61999ca1/py/plugins/pylint.py#L25

On the other hand, the use of `--score=no` and `grep -v '^\** Module'` could make debugging easier in some cases.  Thanks for the suggestion!

**Comment by praiskup** [comment]
Yes, it doesn't make sense to track it.  Sorry for noise.

**Comment by kdudka** [comment]
The `--score=no` option is not available in EPEL-7 pylint, so we cannot use it unconditionally.  But I will insert the grep-based filter for `^\** Module`, which should be both safe and useful.
