### ISSUE TITLE
csbuild and --git-commit-range don't work for out of source builds

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#7]
csbuild and --git-commit-range don't work for out of source builds for example which cmake encourages.

So the line: `repo = git.Repo(".")` fails. Either this should look in the parent directories or your provide an option to tell it where to find it.

**Comment by cryptomilk** [comment]
I've checked git. I uses getcwd() and then walks up the directory tree till it find a .git repo or reaches /

**Comment by kdudka** [comment]
This used to work fine before GitPython changed the behavior in a backward-incompatible way.   #10 will make it work again for all supported versions of GitPython.
