### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by cryptomilk** [kdudka/csmock#8]
The manpage doesn't say in which format GIT_COMMIT_RANGE should be, there should be an example for it.

Also default values should be indicated, e.g.:

```
--added-exit-code ADDED_EXIT_CODE
              exit code to return if there is any defect added in the new version (default: 0)
```

**Comment by kdudka** [comment]
The default value for `--added-exit-code` is actually 7.  #11 updates the documentation.
